### ISSUE TITLE
Issue 1: User can View the home page without logging in. 

### ISSUE THREAD

**Issue by nmotamedi** [nmotamedi/MatchBoxd#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the home page without logging in. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user will see the header bar, a section of recent community activity, and a section of popular films. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2024-04-15 at 2 25 34 PM](https://github.com/nmotamedi/MatchBoxd/assets/144378279/02966c5c-b717-4c86-b3f3-244cda8b44f8)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server.ts` to query the DB to pull 6 most recent film activity. 
- [x] Pull film data for each activity TMDb individual film endpoint.
- [x] Update `server.ts` to pull 6 films from popular TMDb endpoint. 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Adding route for Home page.
- [x] Create a component for Home page.
- [x] Create a component for Header Component.
- [x] Link to correct routes in Header. 
- [x] Create a component for film icon list that can be reused for 6, 36, and 4 icons. 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
