### ISSUE TITLE
Issue 6 - User can can find their most compatible user among all site accounts

### ISSUE THREAD

**Issue by nmotamedi** [nmotamedi/MatchBoxd#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can can find their most compatible user among all site accounts
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User can can click on the comparison tab in the header and view their most compatible user among all site accounts and see recommendations from that user, and the ability to follow that user if not already following. 

User can can click on the comparison tab in the header and view their most compatible user among all site accounts and see recommendations from that user, and the ability to follow that user if not already following. 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.
<img width="529" alt="Screen Shot 2024-04-21 at 2 47 22 PM" src="https://github.com/nmotamedi/MatchBoxd/assets/144378279/d6f13ad2-e49a-4f99-8adf-4eb889e512e0">

<img width="529" alt="Screen Shot 2024-04-21 at 2 47 22 PM" src="https://github.com/nmotamedi/MatchBoxd/assets/144378279/d6f13ad2-e49a-4f99-8adf-4eb889e512e0">
## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server.js` to include an endpoint that queries the database for all filmLogs ordered by userId, then run correlation of activeUser vs. all other users that have seen a minimum of 30 of the same movies.
   - [x] Need to clean data to limit arrays to only rating of the same movies. 
   - [x] Return details of the ideal comparison. 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update app.tsx component to include SetBestComparison and fetch in useEffect. Send result of comparison into Comparison component.
- [x] Update data.ts to include fetch. 
- [x] Create a component to display the comparison, with profile information, past ratings, past reviews, and recommendations. 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
