### ISSUE TITLE
Issue 7: User can submit a new rating.

### ISSUE THREAD

**Issue by nmotamedi** [nmotamedi/MatchBoxd#13]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can submit a new rating.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can submit a new rating. They can click on the rating component, click liked, click their rating, those icons will populate, and can click into review to add a review. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="525" alt="Screen Shot 2024-04-22 at 2 08 03 PM" src="https://github.com/nmotamedi/MatchBoxd/assets/144378279/5b38137e-b535-4dec-8ac4-27cba6798cdc">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server.js` to add an endpoint for posting a review. 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update the rating component to add a button if a rating is being added. 
   - [x] Add event handlers to icons for log, like, ratings. - Maybe make them radio icons. [Link](https://stackoverflow.com/questions/17541614/use-images-instead-of-radio-buttons/17541916#17541916)
   - [x] Half star ratings 
   - [x] Add modal that opens when Review is clicked.
   - [x] Click handler for submit. 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
