### ISSUE TITLE
Issue 8 - User can view their past activity on the filmDetails page, view their past reviews in the review page, view their comparators' reviews on the comparison page, view their following's ratings on the recent films catalog and recommendations page, view their watched films on the watched films page.

### ISSUE THREAD

**Issue by nmotamedi** [nmotamedi/MatchBoxd#17]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view their past activity on the filmDetails page, view their past reviews in the review page, view their comparators' reviews on the comparison page, view their following's ratings on the recent films catalog and recommendations page, view their watched films on the watched films page.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user enters the homepage, they can see the most recent activity of their connections, along with their names and their 5 star rating. Then, if they click into any filmDetails page, they will be able to see their past rating populated in the ratingComponent, with different text (liked, logged, view review.). If they submit a new review, these changes will be made as well. They can also click into their reviews page and see their most recent reviews. In the tab on the wishlist, they can also see all movies they have logged. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `data.sql` to include some reviews for each profile. 

### ☁️ Server Tasks

- [x] Update `server.js` to include endpoint for pull all recent reviews.
- [x] Update `server.js` to include endpoint for pull logs for a specific filmId and UserId.
- [x] Update `server.js` to include endpoint for pull all distinct movies on filmLog for a userId. 
- [x] Refactor /api/films/recent to /api/films/ratings/recent
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to show all films watched.
- [x] Create a component to show all reviews. 
- [x] Update wishlist component to link to film list if clicked on top header. 
- [x] Update filmDetails component to pull filmLog for userId and filmId. Add isWatched to state and change text of form component if isWatched. Do not populate submit button. 
   - [x] Update component to update isReviewing when stars are clicked.  
   - [x] Populate rating component with rating data
   - [x] Fix thumb
- [ ] Update catalog component to accept number of stars and username 

### 🧑‍⚕️ Clean Up Tasks

- [ ] Fix director data. 
- [x] Fix film typo in search
- [x] Refactor /api/compare
- [x] Clean up spelling of comparitor 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
