### ISSUE TITLE
Issue 9: User can view their own profile as well as those of other users. 

### ISSUE THREAD

**Issue by nmotamedi** [nmotamedi/MatchBoxd#19]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

 User can view their own profile as well as those of other users. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

If a user clicks on their own profile header, they can see their profile from other users' perspectives and are given the option to sign out. They can also click on any other user's profile and see their activity. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="871" alt="Screen Shot 2024-04-28 at 10 38 57 PM" src="https://github.com/nmotamedi/MatchBoxd/assets/144378279/e5bd9c1b-811f-4ac8-b4a4-16322de38e41">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `data.sql` to include reviews on each user. 

### ☁️ Server Tasks

- [x] Update `server.js` to update endpoints for pulling review data to allow for different userIds. 
- [x] Refactor functions in comparison to be reused in profile. 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client
- [x] Refactor verify endpoint to be reused in the profile details.

### ⚡ Client Tasks

- [x] Update profile component to populate profile data. Get userId from url params. If User.UserId = userId, populate sign out button. 
- [x] Update data.ts to read users' data for profile
- [x] Put in appropriate icons for the follow/isfollowing
- [x] Handle follow click. 
- [x] Styling

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
