### ISSUE TITLE
issue 10: user can edit or delete a filmLog

### ISSUE THREAD

**Issue by nmotamedi** [nmotamedi/MatchBoxd#21]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

user can edit or delete a filmLog

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks into a film details page that has been logged, a button will populate that deletes. If anything is changed, another button will populate that will provide an option to edit. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server.js` to include endpoint for put a filmLog
- [x] Update `server.js` to include endpoint for delete a filmLog
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update data.ts component to include handle delete. 
- [x] Update ratingComponent to populate delete button at correct time.
- [x] Update data.ts component to include handle edit. 
- [x] Update ratingComponent to populate edit buttons at correct time.
- [x] Add handle delete click. 
- [x] and handle edit click

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
