### ISSUE TITLE
Refactor: Fixes 2

### ISSUE THREAD

**Issue by nmotamedi** [nmotamedi/MatchBoxd#23]
## ✅ Task List

> ##### Check list items that need to be done in order to complete the refactor.

- [x] Follow along with Robert's comments. 
   - [x] Catalog - Magic number 18 turn into a const
   - [x] Fail fast - If (user) to if (!user) return; return as well as alert, instead of an else block. 
      - [x] Film Details
      - [x] data.ts
   - [x] Film Details - if (isOnWatchlist) req.method = 'DELETE';
   - [x] Button onClick - does it need to be optional?
   - [x] Poster_path vs filmPosterPath
   - [x] Return type for server functions
   - [x] SQL indenting 
   - [x] Express Router
   - [x] react-hook-forms / Adding form tags back into rating component
   - [x] Button.tsx notes
   - [x] saveToken / saveUser local / session storage
   - [x] read, fetch, load prefixes instead of get
   - [x] Return await resp.json instead of 2 lines
   - [x] isWishlist / isFollower boolean
- [x] Comparison Component Refactor 
   - [x] Add main component logics to separate function file that can be called by both endpoints.  
   - [x] Add lengthy documentation/comment at the top of this function that explains what the code is doing and why that will produce a valid comparison.
   - [ ] Mess around with various other algos.
- [x] Directors isn’t always correct. Filter by job. 
- [x] Add in validate password requirements 
- [x] Add hover cursor to username and profile icon in Comparison
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
