### ISSUE TITLE
Design Update: Media query

### ISSUE THREAD

**Issue by nmotamedi** [nmotamedi/MatchBoxd#25]
## ⚙️ Feature

> ##### Which feature is affected by this update?

All Features

## 📐 Plan

> ##### Summary of the technical approach to be taken.

Handle media queries to have pages appear in vertical line order in mobile

## 🖼️ Wireframes

> ##### Updated wireframe(s) of what the app should look like when the updates are ready.

<img width="271" alt="Screen Shot 2024-04-30 at 11 05 56 PM" src="https://github.com/nmotamedi/MatchBoxd/assets/144378279/503aca30-f690-4a57-9acb-160fe017c928">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Media query handling
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that don't do anything.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile **and** desktop screen sizes for inclusion in the Pull Request.
