### ISSUE TITLE
Issue 11: User can see other user's ratings in recommendation and recent films

### ISSUE THREAD

**Issue by nmotamedi** [nmotamedi/MatchBoxd#28]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see other user's ratings in recommendation and recent films
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
on the home page and on the recommendation row of comparison, the ratings will show up as stars under the posterimage. In the home page, the user's profileIcon will show as well. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

Server - Add username to getRecentFilm.

### ⚡ Client Tasks

- [x] Update catalog component to populate stars based on the rating passed on if any and userName if passed on. 
- [x] Update home page to send rating and Username in recent film. 
- [x] Update catalog recommendation to send rating to component. 

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
