### ISSUE TITLE
Issue 2 - User can Click on any film card to see details about the film.

### ISSUE THREAD

**Issue by nmotamedi** [nmotamedi/MatchBoxd#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can Click on any film card to see details about the film.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can click on the film card. This will take them to a separate page with a large picture of the film, film title, actors, crews, where it is streaming, etc. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="894" alt="Screen Shot 2024-04-16 at 10 26 18 AM" src="https://github.com/nmotamedi/MatchBoxd/assets/144378279/caa8decd-4e7f-4cc8-a5fa-13409ab58082">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server.js` to include an endpoint for Cast/Crew from TMDB.
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client - 400 if no id.

### ⚡ Client Tasks

- [x] Add a route for a film details page that takes :filmID as a param.
- [x] Add cast and crew list to FilmDetail type.
- [x] Create a component page for the film details page. 
- [x] Set useEffect and UseState to get filmDetails from TMDB details and people endpoints. 
- [x] Create JSX for page.
- [x] Update Card/Home.tsx onClick to navigate to details page with filmId attached. 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Add in route for Not Found.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
