### ISSUE TITLE
Issue 3 - User can sign up and log in from the header bar, and the home page changes whether or not user is logged in. 

### ISSUE THREAD

**Issue by nmotamedi** [nmotamedi/MatchBoxd#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can sign up and log in from the header bar, and the home page changes whether or not user is logged in. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When they click into the the main page, the user will be taken to a landing page where they can see 6 popular films and a large image. They can log in or sign in from the top header. Sign in will pull down a form, and sign up will open a modal. They could continue to see film details whether or not they are logged in. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="717" alt="Screen Shot 2024-04-16 at 5 36 46 PM" src="https://github.com/nmotamedi/MatchBoxd/assets/144378279/89d60867-1912-4541-84fb-595ff051e0b5">
<img width="719" alt="Screen Shot 2024-04-16 at 5 36 36 PM" src="https://github.com/nmotamedi/MatchBoxd/assets/144378279/503529c2-5036-4ea5-9c01-30f2bec1bd68">
<img width="720" alt="Screen Shot 2024-04-16 at 5 36 27 PM" src="https://github.com/nmotamedi/MatchBoxd/assets/144378279/58b988b7-f52c-4b43-8c17-d712bb3326c6">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server.js` to include endpoints for sign up and sign in. 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to handle modal sign up.
- [x] Create a form component to handle sign in.
- [x] Update header component to change based on signed in or not. 
- [x] Update Home page to change based on signed in or not. 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
