### ISSUE TITLE
Issue 4 - Users can add/delete films to a wishlist.

### ISSUE THREAD

**Issue by nmotamedi** [nmotamedi/MatchBoxd#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can add/delete films to a wishlist.
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
By clicking on the UserClock icon on film details, the film gets added to the wishlist table in DB. They can view their wishlist films by clicking on the Wishlist tab on the header. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="909" alt="Screen Shot 2024-04-17 at 10 21 15 PM" src="https://github.com/nmotamedi/MatchBoxd/assets/144378279/68bfb51d-6e83-4c08-8786-f8d6dc5120a7">
<img width="894" alt="Screen Shot 2024-04-16 at 10 26 18 AM" src="https://github.com/nmotamedi/MatchBoxd/assets/144378279/6e131390-3f9e-48d3-b5a9-d1ae129efb1c">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Update `server.js` to include endpoint for post to wishlist. 
- [x] Update 'server.js' to include endpoint for delete from wishlist. 
- [x] Update 'server.js' to include endpoint for get wishlist where userId = userId. 
- [x] Update 'server.js' to include endpoint for get wishlist where userId=userId and filmId = filmId. - _Maybe join table to get film log as well?_
- [x] Add authorization to any DB calls. 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Update film details component to add film to wishlist if logged in. Send an alert to log in if not. 
   - [x] If clicked when film is already in the wishlist, delete from wishlist. 
- [x] _Add call to wishlist to pull any activity for current user and the film in filmDetails. Populate wishlist icon with correct color if on wishlist._
- [x] Create a component to display all wishlist items pagified by numbers of 18.

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
