### ISSUE TITLE
Issue 5 - User can search from whatever page. Search results will display both minimal film data (photo, title, year, tagline) and users to follow with an opportunity to hit a follow button. 

### ISSUE THREAD

**Issue by nmotamedi** [nmotamedi/MatchBoxd#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search from whatever page. Search results will display both minimal film data (photo, title, year, tagline) and users to follow with an opportunity to hit a follow button. 
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
On the header, there is a search bar. User can search from whatever page. Search results will display both minimal film data (photo, title, year, tagline) and users to follow with an opportunity to hit a follow button. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

- [x] Update `data.sql` to seed user Data. 

### ☁️ Server Tasks

- [x] Update `server.js` to include an API search call to TMDb search endpoint. 
- [x] Update `server.js` to create an endpoint to search for users by username. 
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client.

### ⚡ Client Tasks

- [x] Create a component to display search results. 
- [x] Update header to open search bar when magnifying glass is clicked. Create form component for search. 

### 🧑‍⚕️ Clean Up Tasks

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
